### PR TITLE
Replacement fix

### LINKED ISSUE #164: Fix replacements for dogeument/windoge
Related to #161 , `dogeument` and `windoge` also get replaced everywhere. Splitting it here since the fix will be different than the way `pawse` is fixed.

This one is a bit trickier since `window.location;` won't qualify as a `djs` source within the parser, so we have to either modify the input directly OR modify what we think "isDogescript" to let the parser continue. 

Otherwise, the regex transform is gonna get a bit complex.

### PR DESCRIPTION
**Pull request by AnEmortalKid**
Fixes #164 

Couldn't think of a better solution. 

Maybe the regexp that I was creating didn't match what https://regex101.com/r/dGW9J6/2 had, `'[^\s]*'+key+'[^\s]*'` wasn't doing the trick for me and matching on `plz dogeument.write` (with the plz within it).

### CODE REVIEW

File: lib/parser.js [hunk 1]
```diff
@@ -900,7 +900,22 @@ module.exports = function parse (line) {
 
     // replace custom keywords
     Object.keys(replacements).forEach(function(key) {
-        line = line.replace(new RegExp(key,'g'), replacements[key])
+
+        // preprocess tokens and replace special names
+        line = line.replace(/'[^']+'|\S+/g, function (match, part, str) {
```
Comment (vpzomtrrfrt) [inline lib/parser.js]: Since the same regex is used below for splitting keys, why not just modify keys below?

Comment (AnEmortalKid) [reply lib/parser.js]: The way we return “line” in certain parts, particularly when things aren’t dogescript it ends up messing with the leading whitespaces. I tried it just modifying the keys and ended up finding that the return of line messed things up. 

If we don’t care about preserving white space then we can just use joinKeys instead of line everywhere and simplify stuff! 

I actually prefer that option , and since not many consumers will use 2.4 I guess those passthrough returns wouldn’t matter. 

Another option would be to assume everything is dogescript and have a ‘nodoge’ mode that doesn’t modify the text.

Comment (vpzomtrrfrt) [reply lib/parser.js]: Whitespace isn't handled all that well right now, but I think it would be better to have similar output to older versions for now

Comment (AnEmortalKid) [reply lib/parser.js]: Ok! We can leave the fiddling with line then! If you can think of a cleaner regex we can try that too.
